### ISSUE TITLE
license & credits question

### ISSUE THREAD

**Issue by brunob** [onozaty/firefox-delicious-incsearch#1]
Hi @onozaty and thanks for this great addon i've used for many years.

I've forked your project here https://github.com/seenthis/firefox-seenthis-search in order to plug it to http://seenthis.net/ and would like to know how do you like to be credited ? For now i've credited your work in the readme file of the repo.

I've seen that libs used in the project are distributed under MIT license, are you ok if i use the same license for our fork ?

Thanks again :)

**Comment by onozaty** [comment]
Hi @brunob.

> For now i've credited your work in the readme file of the repo.
> I've seen that libs used in the project are distributed under MIT license, are you ok if i use the same license for our fork ?

It is okay.
I'm glad to be of help in your project :)

**Comment by brunob** [comment]
Great, thx a lot @onozaty :)
